#!/usr/bin/env python3
"""Train and evaluate a walk-forward legal FPL action-value policy.

The forecast cache for each season is fitted only on seasons before that
season. Counterfactual action labels are generated by replaying legal hold,
transfer, and chip candidates through the simulator. The final 2025/26
season is never used for fitting or model selection.
"""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
import json
from pathlib import Path
import sys
from typing import Any

import joblib
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from fpl_lab.player_models import (
    _extended_feature_columns,
    _fit_extended_neural,
    _fit_extended_ridge,
    build_extended_player_feature_table,
    load_vaastav_gameweeks,
)
from fpl_lab.benchmark_forecast import (
    build_benchmark_feature_table,
    build_gameweek_forecast_rows,
    fit_benchmark_forecast_models,
)
from fpl_lab.context import ContextStore, load_context_events
from fpl_lab.elite_managers import (
    load_observed_manager_transitions,
    summarize_observed_manager_transitions,
)
from fpl_lab.official_archive import OfficialSnapshotStore
from fpl_lab.policy import ActionValueEnsemble
from fpl_lab.policy_training import (
    collect_counterfactual_examples,
    counterfactual_target_values,
)
from fpl_lab.simulator import (
    build_model_signal_cache,
    build_season_data,
    build_signal_cache,
    simulate_season,
)


def season_order(season: str) -> int:
    return int(season.split("-")[0])


def _distinct_player_gameweeks(frame: pd.DataFrame) -> pd.DataFrame:
    """Use one row per player/GW for gameweek-level targets and prices."""

    return frame.sort_values(["player_season_key", "sequence"]).drop_duplicates(
        ["player_season_key", "sequence"], keep="last"
    )


def _forecast_caches(
    raw: pd.DataFrame,
    seasons: list[str],
    feature_frame: pd.DataFrame | None,
    forecast_model_kind: str = "neural",
    context_store: ContextStore | None = None,
    quality_rows: list[dict[str, Any]] | None = None,
    benchmark_feature_frame: pd.DataFrame | None = None,
) -> dict[str, dict[int, list]]:
    """Build a no-lookahead forecast cache for every requested season."""

    caches: dict[str, dict[int, list]] = {}
    season_data = {season: build_season_data(raw, season) for season in seasons}
    for season in seasons:
        current = season_data[season]
        prior_seasons = [candidate for candidate in seasons if season_order(candidate) < season_order(season)]
        previous = season_data[prior_seasons[-1]] if prior_seasons else None
        if not prior_seasons:
            caches[season] = build_signal_cache(current, previous, context_store=context_store)
            continue
        print(f"  fitting {forecast_model_kind} point/horizon/price models for {season}", flush=True)
        if forecast_model_kind == "external_hgb":
            if benchmark_feature_frame is None:
                raise ValueError("external_hgb requires benchmark_feature_frame")
            train = benchmark_feature_frame[benchmark_feature_frame["season"].isin(prior_seasons)].copy()
            target = benchmark_feature_frame[benchmark_feature_frame["season"] == season].copy()
            benchmark_models = fit_benchmark_forecast_models(train)
            forecast_rows = build_gameweek_forecast_rows(target, benchmark_models)
            caches[season] = build_model_signal_cache(current, forecast_rows)
            if quality_rows is not None:
                actual = pd.to_numeric(target["total_points"], errors="coerce").to_numpy(float)
                predicted = benchmark_models.predict_expected_points(target)
                quality_rows.append(
                    {
                        "season": season,
                        "target": "benchmark_expected_points_per_fixture",
                        "n": int(len(actual)),
                        "rmse": float(np.sqrt(np.mean((actual - predicted) ** 2))),
                        "mae": float(np.mean(np.abs(actual - predicted))),
                        "actual_mean": float(np.mean(actual)),
                        "predicted_mean": float(np.mean(predicted)),
                    }
                )
            continue
        train = feature_frame[feature_frame["season"].isin(prior_seasons)].copy()
        target = feature_frame[feature_frame["season"] == season].copy()
        gameweek_train = _distinct_player_gameweeks(train)
        if forecast_model_kind == "neural":
            forecast_model = _fit_extended_neural(train)
            short_model = _fit_extended_neural(
                gameweek_train.dropna(subset=["target_horizon_points_3"]),
                target="target_horizon_points_3",
            )
            long_model = _fit_extended_neural(
                gameweek_train.dropna(subset=["target_horizon_points_8"]),
                target="target_horizon_points_8",
            )
        elif forecast_model_kind == "ridge":
            forecast_model = _fit_extended_ridge(train, alpha=60.0)
            short_model = _fit_extended_ridge(
                gameweek_train.dropna(subset=["target_horizon_points_3"]),
                alpha=60.0,
                target="target_horizon_points_3",
            )
            long_model = _fit_extended_ridge(
                gameweek_train.dropna(subset=["target_horizon_points_8"]),
                alpha=60.0,
                target="target_horizon_points_8",
            )
        else:
            raise ValueError(f"unknown forecast_model_kind: {forecast_model_kind}")
        # Availability is a separate supervised model rather than a proxy
        # copied from the last five minutes.  It is trained on one row per
        # player/gameweek, so a double gameweek contributes one aggregated
        # outcome and cannot duplicate a player in the availability labels.
        availability_train = gameweek_train.dropna(subset=["target_minutes_gw"])
        expected_minutes_model = _fit_extended_ridge(
            availability_train,
            alpha=40.0,
            target="target_minutes_gw",
        )
        short_minutes_model = _fit_extended_ridge(
            gameweek_train.dropna(subset=["target_horizon_minutes_3"]),
            alpha=40.0,
            target="target_horizon_minutes_3",
        )
        long_minutes_model = _fit_extended_ridge(
            gameweek_train.dropna(subset=["target_horizon_minutes_8"]),
            alpha=40.0,
            target="target_horizon_minutes_8",
        )
        forecast_rows = target.copy()
        forecast_rows["extended_selected"] = forecast_model.predict(_extended_feature_columns(target))
        forecast_rows["forecast_short_expected_points"] = short_model.predict(_extended_feature_columns(target))
        forecast_rows["forecast_long_expected_points"] = long_model.predict(_extended_feature_columns(target))
        forecast_rows["forecast_expected_minutes"] = np.clip(
            expected_minutes_model.predict(_extended_feature_columns(target)), 0.0, 180.0
        )
        forecast_rows["forecast_short_expected_minutes"] = np.clip(
            short_minutes_model.predict(_extended_feature_columns(target)), 0.0, 540.0
        )
        forecast_rows["forecast_long_expected_minutes"] = np.clip(
            long_minutes_model.predict(_extended_feature_columns(target)), 0.0, 720.0
        )
        if quality_rows is not None:
            target_gameweek = _distinct_player_gameweeks(target)
            quality_specs = (
                ("expected_minutes_gw", "target_minutes_gw", expected_minutes_model, 180.0),
                ("expected_minutes_3gw", "target_horizon_minutes_3", short_minutes_model, 540.0),
                ("expected_minutes_8gw", "target_horizon_minutes_8", long_minutes_model, 720.0),
            )
            target_features = _extended_feature_columns(target_gameweek)
            for name, target_column, model, upper_bound in quality_specs:
                actual = pd.to_numeric(target_gameweek[target_column], errors="coerce").to_numpy(float)
                predicted = np.clip(model.predict(target_features), 0.0, upper_bound)
                quality_rows.append(
                    {
                        "season": season,
                        "target": name,
                        "n": int(len(actual)),
                        "rmse": float(np.sqrt(np.mean((actual - predicted) ** 2))),
                        "mae": float(np.mean(np.abs(actual - predicted))),
                        "actual_mean": float(np.mean(actual)),
                        "predicted_mean": float(np.mean(predicted)),
                    }
                )
        price_train = gameweek_train.dropna(subset=["target_price_change"])
        if price_train.empty:
            forecast_rows["future_price_change_ridge"] = 0.0
        else:
            price_model = _fit_extended_ridge(price_train, alpha=10.0, target="target_price_change")
            forecast_rows["future_price_change_ridge"] = price_model.predict(_extended_feature_columns(target))
        caches[season] = build_model_signal_cache(current, forecast_rows)
    return caches


def _collect_examples(
    raw: pd.DataFrame,
    seasons: list[str],
    history_seasons: list[str],
    caches: dict[str, dict[int, list]],
    max_states: int,
    candidate_width: int,
    horizon_gameweeks: int,
    chip_transfer_depth: int,
    starting_modes: tuple[str, ...],
    label_policy: str,
) -> list:
    season_data = {season: build_season_data(raw, season) for season in history_seasons}
    examples = []
    for season in seasons:
        current = season_data[season]
        prior_seasons = [candidate for candidate in history_seasons if season_order(candidate) < season_order(season)]
        previous = season_data[prior_seasons[-1]] if prior_seasons else None
        for mode_index, mode in enumerate(starting_modes):
            print(f"  collecting {season} / {mode}", flush=True)
            trajectory = simulate_season(
                current,
                previous,
                policy=label_policy,
                initial_squad_mode=mode,
                initial_squad_seed=mode_index,
                signal_cache=caches[season],
                chip_transfer_depth=chip_transfer_depth,
            )
            examples.extend(
                collect_counterfactual_examples(
                    current,
                    previous,
                    scenario=f"{season}:{mode}",
                    behavior_policy=label_policy,
                    trajectory_log=trajectory.log,
                    signal_cache=caches[season],
                    horizon_gameweeks=horizon_gameweeks,
                    candidate_width=candidate_width,
                    max_states=max_states,
                    continuation_policy=label_policy,
                    chip_transfer_depth=chip_transfer_depth,
                )
            )
    return examples


def _fit_action_model(examples: list, targets: list[float], n_models: int, hidden: tuple[int, ...]) -> ActionValueEnsemble:
    model = ActionValueEnsemble(
        n_models=n_models,
        hidden_layer_sizes=hidden,
        random_state=42,
        bootstrap_fraction=0.90,
    )
    model.fit(
        [example.state for example in examples],
        [example.action for example in examples],
        targets,
    )
    return model


def _example_metrics(model: ActionValueEnsemble, examples: list, targets: list[float]) -> dict[str, float]:
    predictions = model.predict(
        [example.state for example in examples],
        [example.action for example in examples],
    )
    actual = np.asarray(targets, dtype=float)
    groups: dict[tuple[str, int], list[int]] = defaultdict(list)
    for index, example in enumerate(examples):
        groups[(example.scenario, example.gameweek)].append(index)
    chosen_best = 0
    for indices in groups.values():
        predicted_best = max(indices, key=lambda index: predictions[index])
        actual_best = max(indices, key=lambda index: actual[index])
        chosen_best += int(predicted_best == actual_best)
    return {
        "n": int(len(actual)),
        "rmse": float(np.sqrt(np.mean((actual - predictions) ** 2))),
        "mae": float(np.mean(np.abs(actual - predictions))),
        "state_argmax_accuracy": float(chosen_best / max(1, len(groups))),
    }


def _simulate_policy(
    model: ActionValueEnsemble,
    raw: pd.DataFrame,
    season: str,
    previous_season: str | None,
    cache: dict[int, list],
    modes: tuple[str, ...],
    chip_transfer_depth: int,
    policy: str = "neural",
) -> list[dict[str, Any]]:
    current = build_season_data(raw, season)
    previous = build_season_data(raw, previous_season) if previous_season else None
    rows = []
    for mode_index, mode in enumerate(modes):
        print(
            f"  simulating {policy} / {season} / {mode} "
            f"(chip depth {chip_transfer_depth})",
            flush=True,
        )
        result = simulate_season(
            current,
            previous,
            policy=policy,
            neural_policy=model if policy in {"neural", "cocktail"} else None,
            initial_squad_mode=mode,
            initial_squad_seed=mode_index,
            signal_cache=cache,
            chip_transfer_depth=chip_transfer_depth,
        )
        rows.append(
            {
                "season": season,
                "policy": policy,
                "initial_squad_mode": mode,
                "net_points": result.net_points,
                "gross_points": result.gross_points,
                "hit_points": result.hit_points,
                "transfers": result.transfers,
                "paid_transfers": result.paid_transfers,
                "chip_uses": result.chip_uses,
                "final_bank": result.final_bank,
                "final_squad_value": result.final_squad_value,
            }
        )
    return rows


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--history-root", required=True)
    parser.add_argument("--evaluation-season", default="2025-26")
    parser.add_argument("--validation-season", default="2024-25")
    parser.add_argument("--output-dir", default="runs/action-policy")
    parser.add_argument("--max-states", type=int, default=6, help="states sampled per season and starting mode")
    parser.add_argument("--candidate-width", type=int, default=6)
    parser.add_argument("--horizon-gameweeks", type=int, default=2)
    parser.add_argument("--training-chip-depth", type=int, default=5)
    parser.add_argument("--test-chip-depth", type=int, default=15)
    parser.add_argument(
        "--forecast-model",
        choices=("neural", "ridge", "external_hgb"),
        default="neural",
        help="walk-forward forecast family; external_hgb reproduces the published minutes-plus-conditional-points architecture without LightGBM",
    )
    parser.add_argument(
        "--label-policy",
        choices=("points_only", "points_only_free_only"),
        default="points_only",
        help="legal behavior policy used to generate states and continuations; points_only includes paid hits",
    )
    parser.add_argument("--news-context", action="append", default=[], help="backdated news JSON/JSONL/CSV; only events before each simulated deadline are used")
    parser.add_argument("--social-context", action="append", default=[], help="backdated social JSON/JSONL/CSV; only events before each simulated deadline are used")
    parser.add_argument(
        "--official-snapshots",
        default=None,
        help="archived bootstrap player snapshots; only the latest row observed before each deadline is used",
    )
    parser.add_argument(
        "--observed-manager-archive",
        default=None,
        help="optional weekly manager archive used for held-out behavior auditing only, never model fitting",
    )
    parser.add_argument(
        "--observed-manager-rank-index",
        default=None,
        help="rank-band crosswalk for --observed-manager-archive",
    )
    parser.add_argument(
        "--starting-modes",
        nargs="+",
        choices=("points", "value", "template", "randomized_points", "forecast"),
        default=("points", "value", "template", "randomized_points"),
        help="legal opening-squad families used for action labels and evaluation",
    )
    args = parser.parse_args()

    history_root = Path(args.history_root)
    seasons = sorted(
        [path.name for path in history_root.iterdir() if path.is_dir() and (path / "gws").exists()],
        key=season_order,
    )
    for required in (args.validation_season, args.evaluation_season):
        if required not in seasons:
            raise SystemExit(f"missing required season {required!r} under {history_root}")
    development = [season for season in seasons if season_order(season) < season_order(args.validation_season)]
    if not development:
        raise SystemExit("no development seasons remain before validation season")

    print(f"Loading {len(seasons)} seasons", flush=True)
    raw = load_vaastav_gameweeks(history_root, seasons)
    print(f"Loaded {len(raw):,} rows; building temporal forecast caches", flush=True)
    context_events = []
    for path in args.news_context:
        context_events.extend(load_context_events(path, kind="news"))
    for path in args.social_context:
        context_events.extend(load_context_events(path, kind="social"))
    context_store = ContextStore(context_events) if context_events else None
    if context_store is not None:
        print(f"Loaded {len(context_events):,} backdated context events", flush=True)
    official_snapshot_store = (
        OfficialSnapshotStore.from_path(args.official_snapshots)
        if args.official_snapshots
        else None
    )
    if official_snapshot_store is not None:
        print(f"Loaded archived official bootstrap snapshots from {args.official_snapshots}", flush=True)
    observed_manager_summary = None
    if args.observed_manager_archive:
        observed_manager_frame = load_observed_manager_transitions(
            args.observed_manager_archive,
            args.observed_manager_rank_index,
        )
        observed_manager_summary = summarize_observed_manager_transitions(observed_manager_frame)
        print(
            f"Loaded {observed_manager_summary['manager_count']} observed managers "
            f"for holdout behavior audit only",
            flush=True,
        )
    benchmark_feature_frame = None
    if args.forecast_model == "external_hgb":
        print("Building external-style 53-feature forecast table", flush=True)
        benchmark_feature_frame = build_benchmark_feature_table(raw, history_root)
        feature_frame = None
    else:
        feature_frame = build_extended_player_feature_table(
            raw,
            context_store=context_store,
            official_snapshot_store=official_snapshot_store,
        )
    cache_seasons = development + [args.validation_season, args.evaluation_season]
    availability_quality: list[dict[str, Any]] = []
    caches = _forecast_caches(
        raw,
        cache_seasons,
        feature_frame,
        forecast_model_kind=args.forecast_model,
        context_store=context_store,
        quality_rows=availability_quality,
        benchmark_feature_frame=benchmark_feature_frame,
    )
    # Keep the action learner exposed to several legal opening families.  The
    # randomized family is seeded per mode so it is reproducible while still
    # testing whether a policy depends on one unusually favorable opening.
    starting_modes = tuple(args.starting_modes)

    print("Collecting development counterfactuals", flush=True)
    development_examples = _collect_examples(
        raw,
        development,
        cache_seasons,
        caches,
        args.max_states,
        args.candidate_width,
        args.horizon_gameweeks,
        args.training_chip_depth,
        starting_modes,
        args.label_policy,
    )
    development_targets = counterfactual_target_values(development_examples)
    print(f"Development examples: {len(development_examples):,}", flush=True)

    print("Collecting validation counterfactuals", flush=True)
    validation_examples = _collect_examples(
        raw,
        [args.validation_season],
        cache_seasons,
        caches,
        args.max_states,
        args.candidate_width,
        args.horizon_gameweeks,
        args.training_chip_depth,
        starting_modes,
        args.label_policy,
    )
    validation_targets = counterfactual_target_values(validation_examples)
    print(f"Validation examples: {len(validation_examples):,}", flush=True)

    candidate_specs = {
        "small": (3, (32, 16)),
        "default": (5, (64, 32)),
    }
    candidates = {}
    validation_scores = {}
    for name, (n_models, hidden) in candidate_specs.items():
        print(f"Fitting action candidate {name}: {n_models} x {hidden}", flush=True)
        candidate = _fit_action_model(development_examples, development_targets, n_models, hidden)
        candidates[name] = candidate
        validation_scores[name] = _example_metrics(candidate, validation_examples, validation_targets)
        print(json.dumps({name: validation_scores[name]}), flush=True)
    selected_name = min(candidate_specs, key=lambda name: (validation_scores[name]["rmse"], -validation_scores[name]["state_argmax_accuracy"]))

    all_examples = development_examples + validation_examples
    all_targets = development_targets + validation_targets
    n_models, hidden = candidate_specs[selected_name]
    print(f"Refitting selected action model {selected_name} on {len(all_examples):,} examples", flush=True)
    selected_model = _fit_action_model(all_examples, all_targets, n_models, hidden)

    previous_validation = max(development, key=season_order)
    validation_neural = _simulate_policy(
        candidates[selected_name],
        raw,
        args.validation_season,
        previous_validation,
        caches[args.validation_season],
        starting_modes,
        args.training_chip_depth,
        policy="neural",
    )
    validation_anchor = _simulate_policy(
        selected_model,
        raw,
        args.validation_season,
        previous_validation,
        caches[args.validation_season],
        starting_modes,
        args.training_chip_depth,
        policy="points_only_free_only",
    )
    validation_cocktail = _simulate_policy(
        candidates[selected_name],
        raw,
        args.validation_season,
        previous_validation,
        caches[args.validation_season],
        starting_modes,
        args.training_chip_depth,
        policy="cocktail",
    )
    validation_patient_chips = _simulate_policy(
        selected_model,
        raw,
        args.validation_season,
        previous_validation,
        caches[args.validation_season],
        starting_modes,
        args.training_chip_depth,
        policy="patient_chips",
    )
    test_previous = max(cache_seasons[:-1], key=season_order)
    test_neural = _simulate_policy(
        selected_model,
        raw,
        args.evaluation_season,
        test_previous,
        caches[args.evaluation_season],
        starting_modes,
        args.test_chip_depth,
        policy="neural",
    )
    test_anchor = _simulate_policy(
        selected_model,
        raw,
        args.evaluation_season,
        test_previous,
        caches[args.evaluation_season],
        starting_modes,
        args.test_chip_depth,
        policy="points_only_free_only",
    )
    test_cocktail = _simulate_policy(
        selected_model,
        raw,
        args.evaluation_season,
        test_previous,
        caches[args.evaluation_season],
        starting_modes,
        args.test_chip_depth,
        policy="cocktail",
    )
    test_patient_chips = _simulate_policy(
        selected_model,
        raw,
        args.evaluation_season,
        test_previous,
        caches[args.evaluation_season],
        starting_modes,
        args.test_chip_depth,
        policy="patient_chips",
    )

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    joblib.dump(selected_model, output_dir / "action-policy-model.joblib")
    records = []
    for example, target in zip(all_examples, all_targets):
        record = example.to_record()
        record["target"] = target
        records.append(record)
    (output_dir / "counterfactual-examples.json").write_text(json.dumps(records, indent=2) + "\n", encoding="utf-8")
    if args.forecast_model == "external_hgb":
        feature_cache_description = (
            "walk-forward external-style 53-feature minutes classifier plus conditional cameo/60-plus "
            "point regressors; true fixture team reconstruction and persistent player codes; "
            "each season uses only prior seasons for fitting"
        )
    else:
        feature_cache_description = (
            f"walk-forward extended {args.forecast_model} point forecasts, direct 3/8-gameweek forecasts, "
            "a next-gameweek price-change ridge, and a separate expected-minutes ridge; "
            "each season uses only prior seasons for fitting"
        )
    metrics = {
        "development_seasons": development,
        "validation_season": args.validation_season,
        "evaluation_season": args.evaluation_season,
        "target_points": 2413,
        "label_policy": args.label_policy,
        "label_action_counts": dict(
            Counter(example.action_id for example in all_examples)
        ),
        "label_paid_hit_actions": sum(
            1 for example in all_examples if example.action.hit_cost > 0.0
        ),
        "label_multi_transfer_actions": sum(
            1 for example in all_examples if example.action.transfer_count > 1
        ),
        "feature_cache": feature_cache_description,
        "development_examples": len(development_examples),
        "validation_examples": len(validation_examples),
        "context": context_store.summary() if context_store is not None else {"events": 0},
        "observed_manager_benchmark": observed_manager_summary,
        "availability_forecast_quality": availability_quality,
        "candidate_validation_scores": validation_scores,
        "selected_candidate": selected_name,
        "starting_squad_modes": list(starting_modes),
        "validation_neural": validation_neural,
        "validation_anchor": validation_anchor,
        "validation_cocktail": validation_cocktail,
        "validation_patient_chips": validation_patient_chips,
        "test_neural": test_neural,
        "test_anchor": test_anchor,
        "test_cocktail": test_cocktail,
        "test_patient_chips": test_patient_chips,
        "training_chip_depth": args.training_chip_depth,
        "test_chip_depth": args.test_chip_depth,
        "warnings": [
            "This is an action-policy research artifact, not a promoted MCP champion.",
            "The final test season is not used for fitting or candidate selection.",
            f"Wildcard/free-hit search depth is {args.test_chip_depth} on the final test and {args.training_chip_depth} during development label generation.",
        ],
    }
    (output_dir / "metrics.json").write_text(json.dumps(metrics, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(metrics, indent=2))


if __name__ == "__main__":
    main()
